name: "CodeSent Scan Action"
description: "Uploads Apigee API proxies to CodeSent for security scanning"
author: "Nikita Markevich @ CodeSent"

inputs:
  api-key:
    description: "CodeSent API Key"
    required: true
  github-token:
    description: "GitHub Token for commenting on PR and creating issue"
    required: true
  proxy-directory:
    description: "Path to the Apigee proxy directory (default: apiproxy)"
    required: false
    default: "apiproxy"

permissions:
  contents: read
  pull-requests: write

runs:
  using: "node20"
  main: "index.js"
