name: "CodeSent Scan Action"
description: "Uploads Apigee API proxies to CodeSent for security scanning and comments results in PR."
author: "Nikita Markevich @ CodeSent"

inputs:
  api-key:
    description: "CodeSent API Key"
    required: true
  github-token:
    description: "GitHub Token for commenting on PR"
    required: true

permissions:
  contents: read
  pull-requests: write

runs:
  using: "node20"
  main: "index.js"